force-app/main/default/objects/Account/recordTypes/Comunidad.recordType-meta.xml
<RecordType>
    <fullName>Comunidad</fullName>
    <active>true</active>
    <label>Comunidad</label>
</RecordType>

force-app/main/default/objects/Case/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <inlineHelpText>Enter your country of residence</inlineHelpText>
    <label>País</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alemania</fullName>
            </value>
            <value>
                <fullName>Bélgica</fullName>
            </value>
            <value>
                <fullName>Brasil</fullName>
            </value>
            <value>
                <fullName>Centro América/Caribe</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
                <default>true</default>
                <label>Chile</label>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Corea</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>España</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Italia</fullName>
            </value>
            <value>
                <fullName>Japón</fullName>
            </value>
            <value>
                <fullName>Marruecos</fullName>
            </value>
            <value>
                <fullName>Medio Oriente</fullName>
            </value>
            <value>
                <fullName>México</fullName>
            </value>
            <value>
                <fullName>Norte de África</fullName>
            </value>
            <value>
                <fullName>Oceanía</fullName>
            </value>
            <value>
                <fullName>Otros Países de África</fullName>
            </value>
            <value>
                <fullName>Otros Países de América del Sur</fullName>
            </value>
            <value>
                <fullName>Otros Países de Asia</fullName>
            </value>
            <value>
                <fullName>Otros Países de Europa</fullName>
            </value>
            <value>
                <fullName>Perú</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Sur de África</fullName>
            </value>
            <value>
                <fullName>Tailandia</fullName>
            </value>
            <value>
                <fullName>Turquía</fullName>
            </value>
            <value>
                <fullName>U.A.E.</fullName>
            </value>
            <value>
                <fullName>USA / Canadá</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Telefono_movil__c.field-meta.xml
<CustomField>
    <fullName>Telefono_movil__c</fullName>
    <inlineHelpText>Enter your contact phone. For Chile, use the format 87654321</inlineHelpText>
    <label>Teléfono móvil</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Comunidad.recordType-meta.xml
<RecordType>
    <fullName>Comunidad</fullName>
    <active>true</active>
    <businessProcess>Proceso Comunidades</businessProcess>
    <description>Tipo de registro para casos comunidad</description>
    <label>Comunidad</label>
</RecordType>

force-app/main/default/classes/AsignacionCasoComunidad_Test.cls
@isTest
private class AsignacionCasoComunidad_Test {
	
	@isTest static void test_method_one() {
		
		Id tipoCuenta = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
		Id tipoContacto = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contacto Comunidad').getRecordTypeId();
		Id tipoCaso = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Comunidad').getRecordTypeId();
		//Id tipoOtroCaso = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Others').getRecordTypeId();

		Account cuentaTest = new Account();
		cuentaTest.RecordTypeId = tipoCuenta;
		cuentaTest.FirstName = 'Nombre';
		cuentaTest.LastName = 'Apellido';
		cuentaTest.PersonEmail = 'correo@correo.cl';
		insert cuentaTest;

		Case casoTest = new Case();
		casoTest.Subject = 'Test';
		casoTest.Description = 'Test';
		casoTest.AccountId = cuentaTest.Id;
		casoTest.Telefono_movil__c = '12345678';
		casoTest.Pais__c = 'Chile';
		insert casoTest;

	}
	
}