force-app/main/default/objects/Account/recordTypes/Empresa.recordType-meta.xml
<RecordType>
    <fullName>Empresa</fullName>
    <active>true</active>
    <label>Empresa</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Contact__c/Notification_Contact__c.object-meta.xml
<CustomObject>
    <label>Notification Contact</label>
    <nameField>
        <label>Notification Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Contact__c/fields/Notification_Account__c.field-meta.xml
<CustomField>
    <fullName>Notification_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notification Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notification Contacts</relationshipLabel>
    <relationshipName>Notification_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Contact__c/fields/Notification_Contact__c.field-meta.xml
<CustomField>
    <fullName>Notification_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Notification Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notification Contacts</relationshipLabel>
    <relationshipName>Notification_Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Contact__c/fields/Notification_Group__c.field-meta.xml
<CustomField>
    <fullName>Notification_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notification Group</label>
    <referenceTo>Notification_Group__c</referenceTo>
    <relationshipLabel>Notification Contacts</relationshipLabel>
    <relationshipName>Notification_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Group__c/Notification_Group__c.object-meta.xml
<CustomObject>
    <label>Notification Group</label>
    <nameField>
        <label>Notification Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Group__c/fields/Notification_Process__c.field-meta.xml
<CustomField>
    <fullName>Notification_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notification Process</label>
    <referenceTo>Notification_Process__c</referenceTo>
    <relationshipLabel>Notification Groups</relationshipLabel>
    <relationshipName>NotificationGroup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Group__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Send to Customer</fullName>
                <isActive>false</isActive>
                <label>Send to Customer</label>
            </value>
            <value>
                <fullName>Wait to Customer</fullName>
                <isActive>false</isActive>
                <label>Wait to Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Group__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
            </value>
            <value>
                <fullName>With Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Process__c/Notification_Process__c.object-meta.xml
<CustomObject>
    <label>Notification Process</label>
    <nameField>
        <displayFormat>NP-{000000}</displayFormat>
        <label>Notification Process Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Processes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Process__c/fields/Change_date__c.field-meta.xml
<CustomField>
    <fullName>Change_date__c</fullName>
    <label>Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Notification_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Review</fullName>
                <label>Document In Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Document Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Document Rejected</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Notification Rejected</fullName>
            </value>
            <value>
                <fullName>Notification Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Process__c/fields/Technical_Manager__c.field-meta.xml
<CustomField>
    <fullName>Technical_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notification_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Process__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
            </value>
            <value>
                <fullName>With Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Task__c/Notification_Task__c.object-meta.xml
<CustomObject>
    <label>Notification Task</label>
    <nameField>
        <label>Notification Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Task__c/fields/Change_date__c.field-meta.xml
<CustomField>
    <fullName>Change_date__c</fullName>
    <formula>Notification_Group__r.Notification_Process__r.Change_date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Notification_Task__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Acceptance__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>With Comments</fullName>
            </value>
            <value>
                <fullName>No Comments</fullName>
            </value>
            <value>
                <fullName>No Feedback after 20 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Task__c/fields/Customer_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Customer_Acceptance__c</fullName>
    <label>Customer Acceptance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>Notification_Group__r.Notification_Process__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Task__c/fields/Notification_Account__c.field-meta.xml
<CustomField>
    <fullName>Notification_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Notification Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notification Tasks</relationshipLabel>
    <relationshipName>NotificationTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Task__c/fields/Notification_Group__c.field-meta.xml
<CustomField>
    <fullName>Notification_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notification Group</label>
    <referenceTo>Notification_Group__c</referenceTo>
    <relationshipLabel>Notification Tasks</relationshipLabel>
    <relationshipName>NotificationTask</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NotificationGroupSendControllerTEST.cls
@isTest
public class NotificationGroupSendControllerTEST {
    static {
        // section to initialize static values
    }

    @testSetup 
    static void setupMethod() {
        // insert the client
        Account acc = new Account (
            Name = 'Test Account',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Empresa').getRecordTypeId(),
            CurrencyIsoCode = 'USD'
        );
        insert acc;
        
        // insert the contact
        Contact c = new Contact (
            LastName = 'Test Contact',
            CurrencyIsoCode = 'USD',
            AccountId = acc.id,
            Email = 'a@a.cl'
        );
        insert c;

        String name = 'DummyUser';
        Id profileId = [SELECT Id FROM Profile WHERE Name =: 'System Administrator'].Id;
        User userTM = new User(
            Username = name + 'TechUser' + '@sqm.com',
            ProfileId = profileId,
            LastName = name,
            FirstName = name,
            Alias = name.substring(0, Math.min(name.length(), 6)),
            Email = name + String.valueOf(Math.abs(Crypto.getRandomLong())) + '@sqm.com',
            TimeZoneSidKey = 'America/New_York',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_CA'
        );        
        insert userTM;
        
        User userOwner = new User(
            Username = name + 'Owner' + '@sqm.com',
            ProfileId = profileId,
            LastName = name,
            FirstName = name,
            Alias = name.substring(0, Math.min(name.length(), 6)),
            Email = name + String.valueOf(Math.abs(Crypto.getRandomLong())) + '@sqm.com',
            TimeZoneSidKey = 'America/New_York',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_CA'
        );        
        insert userOwner;
        
        // insert notification Process
        Notification_Process__c np = new Notification_Process__c(
            Type__c = 'Simple',
            Change_date__c = Date.today(),
            Description__c = 'test',
        	Ownerid = userOwner.Id,
        	Technical_Manager__c = userTM.Id);
        insert np;
        
        // insert notification group
        Notification_Group__c ng = new Notification_Group__c(
            Name = 'Notification Group',
            Notification_Process__c = np.Id,
            Type__c = 'Simple'
        );
        insert ng;
        
        // insert Notification task
        Notification_Task__c nt = new Notification_Task__c(
            Name = 'Notification Task',
            Notification_Account__c = acc.Id,
            Notification_Group__c = ng.Id,
            Type__c = 'Simple'
        );
        insert nt;
            
        // insert Notification Contact
        Notification_Contact__c nc = new Notification_Contact__c(
            Notification_Account__c = acc.Id,
            Notification_Contact__c = c.Id,
            Name = 'Notification Contact',
            Notification_Group__c = ng.Id
        );
        insert nc;
        
        // insert the file
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.ContentDocumentId = null;
        cv.VersionData = Blob.valueOf('Content File'); 
        cv.Title = 'FileTest';
        cv.PathOnClient = 'FileTest';
        insert cv;
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        cdl.LinkedEntityId = np.Id; 
        cdl.ShareType = 'V';
        insert cdl;
        
        System.runAs(new User(Id = UserInfo.getUserId())) {
            //  insert the template
            EmailTemplate e = new EmailTemplate(
                Name = 'TestTemplate',
                DeveloperName = 'test',
                FolderId = UserInfo.getUserId(),
                TemplateType = 'Text',
                Subject = 'Invoice',
                Body = 'Please find the attached invoice.',
                IsActive = true
            );
            insert e;
        }
    }
    
    /**
    *  @Description: Test the call for the service 
    *  @Autor:       LEC , Deloitte, lcastanedad@deloitte.com
    *  @Date:        26/12/2022
    */
    @isTest
    public static void testControllerWithSuccess(){
        NotificationGroupSendController.RequestSimpleWrapper request = new NotificationGroupSendController.RequestSimpleWrapper();
        request.orgWideEmailAddressName = 'Contacto SQM';
        request.templateName = 'TestTemplate';
        request.whatId = [SELECT Id FROM Notification_Group__c WHERE Name = 'Notification Group' LIMIT 1]?.Id;
        request.parentWhatId = [SELECT Notification_Process__c FROM Notification_Group__c WHERE Name = 'Notification Group' LIMIT 1]?.Notification_Process__c;
        request.listOfNotificationTask = [SELECT Id, Comments__c, Customer_Acceptance__c, Notification_Account__c, Notification_Group__c, Name, Status__c, Type__c FROM Notification_Task__c WHERE Notification_Group__c = :request.whatId];

        Test.startTest();
        List<NotificationGroupSendController.ResponseParamWrapper> response = NotificationGroupSendController.sendEmailToNotificationGroup(new NotificationGroupSendController.RequestSimpleWrapper[] {request});
        
        // we assert buy what governor limits say 
        Test.stopTest();
        
        System.assertEquals(response[0].isSuccess, true, 'Response is False!');
    }

    /**
    *  @Description: Test the controller  with data failure result
    *  @Autor:       LEC , Deloitte, lcastanedad@deloitte.com
    *  @Date:        26/12/2022
    */
    @isTest
    public static void testControllerWithDataFailure(){        
        NotificationGroupSendController.RequestSimpleWrapper request = new NotificationGroupSendController.RequestSimpleWrapper();
        request.orgWideEmailAddressName = 'Contacto SQM';
        request.templateName = 'TestTemplate';
        request.whatId = NULL;
        request.parentWhatId = NULL;
        request.listOfNotificationTask = NULL;

        Test.startTest();
        List<NotificationGroupSendController.ResponseParamWrapper> response = NotificationGroupSendController.sendEmailToNotificationGroup(new NotificationGroupSendController.RequestSimpleWrapper[] {request});
        
        Test.stopTest();

        System.assertEquals(response[0].isSuccess, false, 'Response is True!');
    }
}