force-app/main/default/objects/Account/fields/Account_Date_Last_Transactions__c.field-meta.xml
<CustomField>
    <fullName>Account_Date_Last_Transactions__c</fullName>
    <label>Account Date Last Transactions</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/CChEN_Valido__c.field-meta.xml
<CustomField>
    <fullName>CChEN_Valido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CChEN Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Compliance_Status__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Status__c</fullName>
    <label>Compliance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent to approval</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TaxID__c.field-meta.xml
<CustomField>
    <fullName>TaxID__c</fullName>
    <label>TaxID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Empresa.recordType-meta.xml
<RecordType>
    <fullName>Empresa</fullName>
    <active>true</active>
    <label>Empresa</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account_NPS__c.field-meta.xml
<CustomField>
    <fullName>Account_NPS__c</fullName>
    <label>Account NPS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NPS</fullName>
                <default>true</default>
                <label>NPS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SQM_EnviarEncuestaNPSTest.cls
@isTest(SeeAllData=True)
public class SQM_EnviarEncuestaNPSTest {
    @isTest
    public static void test1(){
        
        Account cuenta = new Account(
          Name = 'Marcelo Cuenta Empresa 01',                            // Account Name
          Account_Date_Last_Transactions__c = System.today(),  // Account Date Last Transactions
          TaxID__c = 'qweqweqwe',                                          // TaxID
          Rating = 'C',                                                    // Rating
          CChEN_Valido__c = false,                                         // CChEN Valid
          Compliance_Status__c = 'New'                                    // Compliance Status
        );
        insert cuenta;
        
        Contact contacto = new Contact(
          AccountId = cuenta.Id,              // Account Name
          Email = 'seidor364@gmail.com',          // Email
          Account_NPS__c = 'NPS',                 // Account NPS
          LastName = 'Prueba'
        );
        insert contacto;
        
        List<Contact> lista = new List<Contact>();
        lista.add(contacto);
        List<List<Contact>> lista2 = new List<List<Contact>>();
        lista2.add(lista);
        SQM_EnviarEncuestaNPS.enviarEncuesta(lista2);
    }
}